name: ESPHome Validate

on:
  push:
  pull_request:

jobs:
  discover:
    name: Discover YAML files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find ESPHome YAMLs
        id: set-matrix
        run: |
          # Find YAML files (exclude common folders if needed)
          files=$(find config/ -maxdepth 1 -name "*.yaml" -not -name "secrets.yaml" -printf 'config/%f\n' | jq -R -s -c 'split("\n")[:-1]')
          echo "Found files: $files"
          echo "files=$files" >> $GITHUB_OUTPUT

  validate:
    name: Validate ${{ matrix.file }}
    needs: discover
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.discover.outputs.files) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create dummy secrets.yaml
        run: |
          cat <<EOF > config/secrets.yaml
          wifi_ssid: "test"
          wifi_password: "test"
          ota_password: "test"
          api_key: "test"
          api_encryption_key: "q83v7l8nV1C9Y2lqkJ3m0W6pRrTtU9xZb4n2c5d8e1A="
          fallback_ap_password: "testtest"
          EOF

      - name: Validate config
        uses: esphome/build-action@v7.2.0
        with:
          yaml-file: ${{ matrix.file }}